### ISSUE TITLE
How to shrink

### ISSUE THREAD

**Issue by Bagronk** [teemoo7/MMM-TomTomCalculateRouteTraffic#2]
Hi, 

I was wondering how to shrink this module a bit. It's to big for my mirror setup but can't seem to find where? 

Kind Regards.

**Comment by teemoo7** [comment]
Hi, thanks for your interest. Well, the module just reuses globally defined css properties for fonts, like `large`, `medium` or `small` in order to keep consistency with the other MM modules. Let me see if I can provide an config option for a quick-win.

**Comment by Bagronk** [comment]
Awesome! Thank you!
