### ISSUE TITLE
"de" refers to the wrong translation

### ISSUE THREAD

**Issue by Gnu76** [teemoo7/MMM-TomTomCalculateRouteTraffic#4]
Hi
In MMM-TomTomCalculateRouteTraffic.js on line 57 "de" refers to your french translation file. 
I had made a de translation file but i don't want to change your file every release you made.

**Comment by teemoo7** [comment]
Hi @Gnu76 , thanks for reporting this issue, I've just fixed it with #5 , please let me know if it does the trick for you (and if the new German translation I've provided is OK 😅).
